[package]
name = "grouplink"
version = "0.1.0"
authors = ["Danny McClanahan"]
edition = "2018"

[dependencies]
libsignal-protocol = { git = "https://github.com/cosmicexplorer/libsignal-client.git", rev = "abecef293f11835c285686f62baf038f8d89ba07" }
rand = "0.7.3"
