[package]
name = "grouplink"
version = "0.1.0"
authors = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
libc = "0.2.94"
libsignal-protocol = { git = "https://github.com/cosmicexplorer/libsignal-client.git", rev = "e22906034ca17d6139344255082ae95068b3edb8" }
rand = "0.7"
prost = "0.7"
bytes = "1"
uuid = "0.8"

[build-dependencies]
prost-build = "0.7"

[dev-dependencies]
futures = "0.3.7"
