[package]
name = "libsignal-protocol-sys"
version = "0.1.0"
authors = ["cosmicexplorer"]
edition = "2018"

[build-dependencies]
# TODO: make this source from spack deps!
bindgen = "0.56.0"

[dependencies]
# TODO: add this to spack deps!
lazy_static = "1"
parking_lot = "0.11.1"
